import type { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  /* Layout */
  container: {
    maxWidth: 800,
    margin: "0 auto",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    fontFamily: "var(--font-family)",
    background: "var(--color-bg)",
    color: "var(--color-text)",
    transition: "background 0.3s ease, color 0.3s ease",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px var(--space-xl)",
    borderBottom: "1px solid var(--color-border)",
  },
  title: {
    margin: 0,
    fontSize: "var(--font-size-lg)",
    fontWeight: 700,
    letterSpacing: 2,
    color: "var(--color-text)",
  },
  nav: { display: "flex", gap: 4 },
  navBtn: {
    background: "none",
    border: "none",
    color: "var(--color-nav-btn)",
    padding: "6px 12px",
    fontSize: 13,
    cursor: "pointer",
    borderRadius: "var(--radius-md)",
    transition: "color var(--transition-fast), background var(--transition-fast)",
  },
  navActive: {
    background: "var(--color-nav-active-bg)",
    border: "1px solid var(--color-nav-active-border)",
    color: "var(--color-nav-active-text)",
    padding: "6px 12px",
    fontSize: 13,
    cursor: "pointer",
    borderRadius: "var(--radius-md)",
    transition: "color var(--transition-fast), background var(--transition-fast)",
  },
  status: { fontSize: "var(--font-size-xs)", color: "var(--color-text-muted)" },
  statusError: { fontSize: "var(--font-size-xs)", color: "var(--color-error)" },

  /* Chat */
  messages: {
    flex: 1,
    overflowY: "auto",
    padding: "var(--space-xl)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-md)",
  },
  empty: { margin: "auto", color: "var(--color-text-muted)", fontSize: "var(--font-size-base)" },
  userBubble: {
    alignSelf: "flex-end",
    background: "var(--color-accent)",
    color: "var(--color-accent-text)",
    padding: "10px var(--space-lg)",
    borderRadius: "var(--radius-bubble)",
    maxWidth: "70%",
    fontSize: "var(--font-size-base)",
    lineHeight: 1.5,
  },
  botBubble: {
    alignSelf: "flex-start",
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    padding: "10px var(--space-lg)",
    borderRadius: "var(--radius-bubble)",
    maxWidth: "70%",
    fontSize: "var(--font-size-base)",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap" as const,
  },
  toolEvents: {
    marginTop: "var(--space-sm)",
    fontSize: "var(--font-size-sm)",
    fontFamily: "var(--font-mono)",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  toolCall: {
    color: "var(--color-tool-call-text)",
    padding: "2px var(--space-sm)",
    background: "var(--color-tool-call-bg)",
    borderRadius: "var(--radius-sm)",
  },
  toolResult: {
    color: "var(--color-tool-result-text)",
    padding: "2px var(--space-sm)",
    background: "var(--color-tool-result-bg)",
    borderRadius: "var(--radius-sm)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  cursor: { animation: "blink 1s step-end infinite" },
  inputBar: {
    display: "flex",
    gap: "var(--space-sm)",
    padding: "var(--space-md) var(--space-xl)",
    borderTop: "1px solid var(--color-border)",
  },
  input: {
    flex: 1,
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-lg)",
    padding: "10px 14px",
    color: "var(--color-text)",
    fontSize: "var(--font-size-base)",
    outline: "none",
  },
  sendBtn: {
    background: "var(--color-accent)",
    color: "var(--color-accent-text)",
    border: "none",
    borderRadius: "var(--radius-lg)",
    padding: "10px var(--space-xl)",
    fontSize: "var(--font-size-base)",
    fontWeight: 600,
    cursor: "pointer",
    transition: "background var(--transition-fast)",
  },
  sendBtnDisabled: {
    background: "var(--color-surface)",
    color: "var(--color-text-muted)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-lg)",
    padding: "10px var(--space-xl)",
    fontSize: "var(--font-size-base)",
    fontWeight: 600,
    cursor: "not-allowed",
  },
  thinkingDots: {
    display: "flex",
    gap: 4,
    padding: "10px var(--space-lg)",
    alignSelf: "flex-start",
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "var(--color-text-muted)",
    animation: "pulse 1.4s ease-in-out infinite",
  },
  voiceBtn: {
    background: "var(--color-surface)",
    color: "var(--color-text)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-lg)",
    padding: "10px 14px",
    fontSize: "var(--font-size-base)",
    cursor: "pointer",
    transition: "background var(--transition-fast)",
    minWidth: 44,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  voiceBtnActive: {
    background: "var(--color-error, #e53e3e)",
    color: "white",
    border: "none",
    borderRadius: "var(--radius-lg)",
    padding: "10px 14px",
    fontSize: "var(--font-size-base)",
    cursor: "pointer",
    minWidth: 44,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    animation: "pulse 1.4s ease-in-out infinite",
  },

  /* Panel views */
  panel: {
    flex: 1,
    overflowY: "auto",
    padding: "var(--space-xl)",
  },
  panelTitle: {
    margin: "0 0 var(--space-lg)",
    fontSize: "var(--font-size-md)",
    fontWeight: 600,
    color: "var(--color-text)",
  },

  /* Search */
  searchBar: { display: "flex", gap: "var(--space-sm)", marginBottom: "var(--space-md)" },
  searchBtn: {
    background: "var(--color-accent)",
    color: "var(--color-accent-text)",
    border: "none",
    borderRadius: "var(--radius-lg)",
    padding: "10px var(--space-xl)",
    fontSize: "var(--font-size-base)",
    fontWeight: 600,
    cursor: "pointer",
  },

  /* Cards */
  card: {
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-xl)",
    padding: 14,
    marginBottom: 10,
  },
  cardHeader: {
    fontSize: "var(--font-size-base)",
    fontWeight: 600,
    color: "var(--color-text)",
    marginBottom: 4,
    display: "flex",
    alignItems: "center",
    gap: "var(--space-sm)",
  },
  badge: {
    fontSize: "var(--font-size-xs)",
    background: "var(--color-surface-hover)",
    color: "var(--color-text-secondary)",
    padding: "2px var(--space-sm)",
    borderRadius: "var(--radius-sm)",
  },
  cardDesc: {
    fontSize: 13,
    color: "var(--color-text-secondary)",
    lineHeight: 1.4,
  },
  cardTriggers: {
    marginTop: "var(--space-sm)",
    display: "flex",
    gap: 4,
    flexWrap: "wrap",
  },
  cardMeta: {
    fontSize: "var(--font-size-xs)",
    color: "var(--color-text-muted)",
    marginTop: 4,
  },

  /* Code */
  pre: {
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-lg)",
    padding: "var(--space-lg)",
    fontSize: 13,
    overflow: "auto",
    color: "var(--color-text-secondary)",
  },

  /* Error */
  errorBanner: {
    background: "var(--color-error-bg)",
    border: "1px solid var(--color-error-border)",
    color: "var(--color-error-text)",
    padding: "10px var(--space-lg)",
    borderRadius: "var(--radius-lg)",
    marginBottom: "var(--space-md)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: 13,
  },
  errorDismiss: {
    background: "none",
    border: "none",
    color: "var(--color-error-text)",
    cursor: "pointer",
    fontSize: 16,
    padding: "0 4px",
  },
  error: {
    color: "var(--color-error-text)",
    fontSize: 13,
    padding: "var(--space-md)",
    background: "var(--color-error-bg)",
    borderRadius: "var(--radius-lg)",
    marginBottom: "var(--space-md)",
  },

  /* Spinner */
  spinner: {
    display: "inline-block",
    width: 16,
    height: 16,
    border: "2px solid var(--color-border)",
    borderTopColor: "var(--color-text)",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },

  /* Filters */
  filterBar: {
    display: "flex",
    gap: "var(--space-sm)",
    marginBottom: "var(--space-md)",
  },
  filterSelect: {
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-md)",
    padding: "6px 10px",
    color: "var(--color-text-secondary)",
    fontSize: "var(--font-size-sm)",
    outline: "none",
  },
  loadMoreBtn: {
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-lg)",
    padding: "8px var(--space-lg)",
    color: "var(--color-text-secondary)",
    fontSize: 13,
    cursor: "pointer",
    width: "100%",
    marginTop: "var(--space-sm)",
  },

  /* Settings */
  section: { marginBottom: 20 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--color-text-secondary)",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: "var(--space-sm)",
    marginTop: "var(--space-lg)",
  },
  statusRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 0",
    borderBottom: "1px solid var(--color-border-subtle)",
    fontSize: 13,
  },
  statusKey: { color: "var(--color-text-muted)" },
  statusVal: { color: "var(--color-text)", fontWeight: 500 },
  statusOk: { color: "var(--color-success)", fontWeight: 500 },
  statusDegraded: { color: "var(--color-warning)", fontWeight: 500 },

  /* Channels */
  channels: { display: "flex", gap: 6, flexWrap: "wrap" },
  chip: {
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-md)",
    padding: "4px 10px",
    fontSize: "var(--font-size-sm)",
    color: "var(--color-text-secondary)",
  },

  /* Textarea */
  textarea: {
    flex: 1,
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-lg)",
    padding: "10px 14px",
    color: "var(--color-text)",
    fontSize: "var(--font-size-base)",
    outline: "none",
    resize: "none",
    fontFamily: "var(--font-family)",
    lineHeight: 1.5,
    maxHeight: 150,
  },

  /* Message actions */
  messageActions: {
    display: "flex",
    gap: 4,
    marginTop: 6,
    paddingTop: 4,
    borderTop: "1px solid var(--color-border-subtle)",
  },
  msgActionBtn: {
    background: "none",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-sm)",
    color: "var(--color-text-muted)",
    fontSize: 11,
    padding: "2px 8px",
    cursor: "pointer",
    transition: "color var(--transition-fast), border-color var(--transition-fast)",
  },

  /* Markdown styles */
  inlineCode: {
    background: "var(--color-surface-hover)",
    padding: "1px 6px",
    borderRadius: "var(--radius-sm)",
    fontSize: 13,
    fontFamily: "var(--font-mono)",
  },
  codeBlock: {
    background: "var(--color-surface-hover)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-md)",
    padding: 12,
    fontSize: 13,
    fontFamily: "var(--font-mono)",
    overflow: "auto",
    margin: "8px 0",
  },
  codeCopyBtn: {
    position: "absolute",
    top: 6,
    right: 6,
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-sm)",
    color: "var(--color-text-muted)",
    fontSize: 10,
    padding: "2px 6px",
    cursor: "pointer",
    zIndex: 1,
  },
  mdLink: {
    color: "var(--color-accent)",
    textDecoration: "underline",
  },
  mdTable: {
    borderCollapse: "collapse",
    width: "100%",
    fontSize: 13,
    margin: "8px 0",
  },
  mdBlockquote: {
    borderLeft: "3px solid var(--color-accent)",
    margin: "8px 0",
    paddingLeft: 12,
    color: "var(--color-text-secondary)",
  },

  /* Sidebar */
  sidebarWrapper: {
    display: "flex",
    height: "100vh",
  },
  sidebar: {
    width: 250,
    minWidth: 250,
    borderRight: "1px solid var(--color-border)",
    display: "flex",
    flexDirection: "column",
    background: "var(--color-surface)",
    height: "100vh",
  },
  sidebarCollapsed: {
    width: 48,
    minWidth: 48,
    borderRight: "1px solid var(--color-border)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 10,
    gap: 8,
    background: "var(--color-surface)",
    height: "100vh",
  },
  sidebarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 12px",
    borderBottom: "1px solid var(--color-border)",
  },
  sidebarToggle: {
    background: "none",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-md)",
    color: "var(--color-text-secondary)",
    cursor: "pointer",
    padding: "4px 8px",
    fontSize: 14,
  },
  sidebarList: {
    flex: 1,
    overflowY: "auto",
    padding: "4px 0",
  },
  sidebarItem: {
    display: "flex",
    alignItems: "center",
    padding: "8px 12px",
    cursor: "pointer",
    fontSize: 13,
    color: "var(--color-text-secondary)",
    transition: "background var(--transition-fast)",
  },
  sidebarItemActive: {
    display: "flex",
    alignItems: "center",
    padding: "8px 12px",
    cursor: "pointer",
    fontSize: 13,
    color: "var(--color-text)",
    background: "var(--color-nav-active-bg)",
    borderLeft: "3px solid var(--color-accent)",
  },
  sidebarDeleteBtn: {
    background: "none",
    border: "none",
    color: "var(--color-text-muted)",
    cursor: "pointer",
    fontSize: 12,
    padding: "2px 4px",
    opacity: 0.6,
  },
  sidebarActionBtn: {
    background: "none",
    border: "none",
    color: "var(--color-text-muted)",
    cursor: "pointer",
    fontSize: 12,
    padding: "2px 4px",
    opacity: 0.6,
  },
  searchInput: {
    width: "100%",
    padding: "6px 8px",
    fontSize: "var(--font-size-sm)",
    background: "var(--color-surface)",
    color: "var(--color-text)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-sm)",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  button: {
    background: "var(--color-surface)",
    border: "1px solid var(--color-border)",
    borderRadius: "var(--radius-lg)",
    padding: "6px 14px",
    color: "var(--color-text)",
    fontSize: "var(--font-size-sm)",
    cursor: "pointer",
    transition: "background var(--transition-fast), border-color var(--transition-fast)",
  },
  loading: {
    padding: "var(--space-xl)",
    color: "var(--color-text-muted)",
    fontSize: "var(--font-size-base)",
    textAlign: "center" as const,
  },
};
