import type { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  container: { maxWidth: 800, margin: "0 auto", height: "100vh", display: "flex", flexDirection: "column", fontFamily: "system-ui, -apple-system, sans-serif", background: "#0a0a0a", color: "#e5e5e5" },
  header: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 20px", borderBottom: "1px solid #262626" },
  title: { margin: 0, fontSize: 18, fontWeight: 700, letterSpacing: 2, color: "#fff" },
  nav: { display: "flex", gap: 4 },
  navBtn: { background: "none", border: "none", color: "#737373", padding: "6px 12px", fontSize: 13, cursor: "pointer", borderRadius: 6 },
  navActive: { background: "#1a1a1a", border: "1px solid #333", color: "#fff", padding: "6px 12px", fontSize: 13, cursor: "pointer", borderRadius: 6 },
  status: { fontSize: 11, color: "#525252" },
  statusError: { fontSize: 11, color: "#ef4444" },
  messages: { flex: 1, overflowY: "auto", padding: 20, display: "flex", flexDirection: "column", gap: 12 },
  empty: { margin: "auto", color: "#525252", fontSize: 14 },
  userBubble: { alignSelf: "flex-end", background: "#2563eb", color: "#fff", padding: "10px 16px", borderRadius: 16, maxWidth: "70%", fontSize: 14, lineHeight: 1.5 },
  botBubble: { alignSelf: "flex-start", background: "#1a1a1a", border: "1px solid #262626", padding: "10px 16px", borderRadius: 16, maxWidth: "70%", fontSize: 14, lineHeight: 1.5, whiteSpace: "pre-wrap" },
  toolEvents: { marginTop: 8, fontSize: 12, fontFamily: "monospace", display: "flex", flexDirection: "column", gap: 2 },
  toolCall: { color: "#facc15", padding: "2px 8px", background: "#1c1917", borderRadius: 4 },
  toolResult: { color: "#4ade80", padding: "2px 8px", background: "#0c1a0c", borderRadius: 4, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  cursor: { animation: "blink 1s step-end infinite" },
  inputBar: { display: "flex", gap: 8, padding: "12px 20px", borderTop: "1px solid #262626" },
  input: { flex: 1, background: "#1a1a1a", border: "1px solid #333", borderRadius: 8, padding: "10px 14px", color: "#e5e5e5", fontSize: 14, outline: "none" },
  sendBtn: { background: "#2563eb", color: "#fff", border: "none", borderRadius: 8, padding: "10px 20px", fontSize: 14, fontWeight: 600, cursor: "pointer" },
  sendBtnDisabled: { background: "#1a1a1a", color: "#525252", border: "1px solid #333", borderRadius: 8, padding: "10px 20px", fontSize: 14, fontWeight: 600, cursor: "not-allowed" },
  panel: { flex: 1, overflowY: "auto", padding: 20 },
  panelTitle: { margin: "0 0 16px", fontSize: 16, fontWeight: 600, color: "#fff" },
  searchBar: { display: "flex", gap: 8, marginBottom: 16 },
  card: { background: "#1a1a1a", border: "1px solid #262626", borderRadius: 10, padding: 14, marginBottom: 10 },
  cardHeader: { fontSize: 14, fontWeight: 600, color: "#fff", marginBottom: 4, display: "flex", alignItems: "center", gap: 8 },
  badge: { fontSize: 11, background: "#262626", color: "#a3a3a3", padding: "2px 8px", borderRadius: 4 },
  cardDesc: { fontSize: 13, color: "#a3a3a3", lineHeight: 1.4 },
  cardTriggers: { marginTop: 8, display: "flex", gap: 4, flexWrap: "wrap" },
  cardMeta: { fontSize: 11, color: "#525252", marginTop: 4 },
  pre: { background: "#1a1a1a", border: "1px solid #262626", borderRadius: 8, padding: 16, fontSize: 13, overflow: "auto", color: "#a3a3a3" },
  errorBanner: { background: "#451a1a", border: "1px solid #7f1d1d", color: "#fca5a5", padding: "10px 16px", borderRadius: 8, marginBottom: 12, display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 13 },
  errorDismiss: { background: "none", border: "none", color: "#fca5a5", cursor: "pointer", fontSize: 16, padding: "0 4px" },
  spinner: { display: "inline-block", width: 16, height: 16, border: "2px solid #333", borderTopColor: "#e5e5e5", borderRadius: "50%", animation: "spin 0.8s linear infinite" },
  thinkingDots: { display: "flex", gap: 4, padding: "10px 16px", alignSelf: "flex-start" },
  dot: { width: 6, height: 6, borderRadius: "50%", background: "#525252", animation: "pulse 1.4s ease-in-out infinite" },
  filterBar: { display: "flex", gap: 8, marginBottom: 12 },
  filterSelect: { background: "#1a1a1a", border: "1px solid #333", borderRadius: 6, padding: "6px 10px", color: "#a3a3a3", fontSize: 12, outline: "none" },
  loadMoreBtn: { background: "#1a1a1a", border: "1px solid #333", borderRadius: 8, padding: "8px 16px", color: "#a3a3a3", fontSize: 13, cursor: "pointer", width: "100%", marginTop: 8 },
  sectionTitle: { fontSize: 13, fontWeight: 600, color: "#a3a3a3", textTransform: "uppercase", letterSpacing: 1, marginBottom: 8, marginTop: 16 },
  statusRow: { display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid #1a1a1a", fontSize: 13 },
  statusKey: { color: "#737373" },
  statusVal: { color: "#e5e5e5", fontWeight: 500 },
  statusOk: { color: "#4ade80", fontWeight: 500 },
  statusDegraded: { color: "#facc15", fontWeight: 500 },
};
