apiVersion: v1
kind: Service
metadata:
  name: mix-engine
  namespace: mix-system
  labels:
    app.kubernetes.io/name: mix-engine
    app.kubernetes.io/component: engine
    app.kubernetes.io/part-of: mix-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mix-engine
  ports:
    - name: http
      port: 18700
      targetPort: http
      protocol: TCP
