"""PyInstaller spec file for MIX Engine (FastAPI + uvicorn)."""

import sys
from pathlib import Path

block_cipher = None

root = Path(SPECPATH).parent
engine_dir = str(root)

a = Analysis(
    [str(root / "engine" / "main.py")],
    pathex=[engine_dir],
    binaries=[],
    datas=[],
    hiddenimports=[
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "engine",
        "engine.api",
        "engine.api.routes",
        "engine.agent",
        "engine.agent.bus",
        "engine.agent.collaboration",
        "engine.agent.decomposer",
        "engine.agent.loop",
        "engine.agent.orchestrator",
        "engine.agent.router",
        "engine.agent.model_router",
        "engine.agent.roles",
        "engine.config",
        "engine.learning",
        "engine.learning.loop",
        "engine.learning.nudge",
        "engine.llm",
        "engine.mcp",
        "engine.mcp.client",
        "engine.memory",
        "engine.memory.store",
        "engine.middleware",
        "engine.middleware.api_key_auth",
        "engine.middleware.rate_limit",
        "engine.middleware.request_logging",
        "engine.monitoring",
        "engine.monitoring.metrics",
        "engine.rag",
        "engine.rag.chunking",
        "engine.rag.citations",
        "engine.rag.collections",
        "engine.rag.pipeline",
        "engine.rag.reranker",
        "engine.sandbox",
        "engine.sandbox.docker",
        "engine.sandbox.local",
        "engine.skills",
        "engine.skills.plugin_context",
        "engine.skills.registry",
        "engine.skills.watcher",
        "engine.tools",
        "engine.tools.approval",
        "engine.tools.bash",
        "engine.tools.calculator",
        "engine.tools.code_execution",
        "engine.tools.composition",
        "engine.tools.dynamic",
        "engine.tools.file",
        "engine.tools.history",
        "engine.tools.image_gen",
        "engine.tools.local",
        "engine.tools.registry",
        "engine.tools.scraper",
        "engine.tools.search",
        "engine.utils",
        "engine.voice",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter", "matplotlib", "numpy", "scipy", "pandas",
        "PIL", "tensorboard", "torch", "tensorflow",
    ],
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="mix-engine",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="mix-engine",
)
